-- 코드를 입력하세요
# WHERE 부분의 CAR_RENTAL_COMPANY_CAR.CAR_ID=CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID 왜 필요?
# JOIN 공부하며 생각해보자.
# SUBSTR 사용법: SUBSTR(A,추출 시작 인덱스,시작으로부터 몇글자까지?)
SELECT DISTINCT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID=CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE='세단'
AND SUBSTR(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,1,7)='2022-10'
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC
