-- 코드를 입력하세요
SELECT DISTINCT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID=CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE='세단'
AND SUBSTR(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,6,2)='10'
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC