-- 코드를 입력하세요
# 문자열 합치기: CONCAT, +(문자열 + 문자열 + ...)
# SELECT의 FROM문에 VIEW를 정의하고 이름 지정 >> SELECT문에서 활용 가능
SELECT CONCAT('/home/grep/src/',UGF.BOARD_ID,'/',CONCAT(FILE_ID,FILE_NAME,FILE_EXT)) AS FILE_PATH
FROM USED_GOODS_BOARD UGB, USED_GOODS_FILE UGF, (SELECT MAX(VIEWS) AS MV FROM USED_GOODS_BOARD) MV
WHERE UGB.BOARD_ID=UGF.BOARD_ID AND VIEWS=MV.MV
ORDER BY FILE_ID DESC