-- 코드를 입력하세요
# DATE_FORMAT 함수: DATE_FORMAT(날짜형 속성, 형태('%Y-%m-%d' 등))
SELECT BOOK_ID, AUTHOR_NAME, SUBSTR(PUBLISHED_DATE,1,10)
FROM BOOK B
INNER JOIN AUTHOR A
ON A.AUTHOR_ID=B.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE
